export const useGameState = () => {
  return {
    stats: {
      tasksCompleted: 0,
      habitsCompleted: 0,
      dailiesCompleted: 0,
      monstersDefeated: 0,
      bossesDefeated: 0,
      totalGoldEarned: 0,
      totalDeaths: 0,
      itemsBought: 0,
      history: [],
      currentStreak: 0,
      maxStreak: 0,
      perfectDays: 0,
      waterDrank: 0,
      exerciseDays: 0,
      cardioSessions: 0,
      healthyMeals: 0,
      stepsMax: 0,
      exerciseHours: 0,
      pagesRead: 0,
      languagePractice: 0,
      meditationHours: 0,
      deepWorkSessions: 0,
      journalEntries: 0,
      noSnoozeDays: 0,
      cosmeticsBought: 0,
      petsOwned: 0,
      realLifeRewardsBought: 0,
      lowHpHeals: 0,
      friendsInvited: 0,
    },
    quests: [],
    inventory: [],
    shopItems: { daily: [], weekly: [], monthly: [] },
    virtualTime: new Date(),
    boughtInRotation: {},
    activeCombat: null,
    completeQuest: () => {},
    takeDamage: () => {},
    addQuest: () => {},
    updateQuest: () => {},
    deleteQuest: () => {},
    buyItem: () => {},
    useItem: () => {},
    updateProfile: () => {},
    adminReset: () => {},
    adminAddGold: () => {},
    adminLevelUp: () => {},
    adminClearInventory: () => {},
    advanceTime: () => {},
    completePenalty: () => {},
    revive: () => {},
    setActiveCombat: () => {},
    winCombat: () => {},
    loseCombat: () => {},
    escapeCombat: () => {},
  };
};