const INITIAL_GAME_STATS: GameStats = {
  tasksCompleted: 0,
  habitsCompleted: 0,
  dailiesCompleted: 0,
  monstersDefeated: 0,
  bossesDefeated: 0,
  totalGoldEarned: 0,
  totalDeaths: 0,
  itemsBought: 0,
  history: [],
  currentStreak: 0,
  maxStreak: 0,
  perfectDays: 0,
  waterDrank: 0,
  exerciseDays: 0,
  cardioSessions: 0,
  healthyMeals: 0,
  stepsMax: 0,
  exerciseHours: 0,
  pagesRead: 0,
  languagePractice: 0,
  meditationHours: 0,
  deepWorkSessions: 0,
  journalEntries: 0,
  noSnoozeDays: 0,
  cosmeticsBought: 0,
  petsOwned: 0,
  realLifeRewardsBought: 0,
  lowHpHeals: 0,
  friendsInvited: 0,
};
＜/dyad-write>

This will fix the syntax error and also the logical error of assigning a type instead of a value.

 Let's write the change.

</think><dyad-write path="src/hooks/use-game-state.tsx" description="Fixing syntax error by replacing semicolons with commas and type annotations with initial values in INITIAL_GAME_STATS">
const INITIAL_GAME_STATS: GameStats = {
  tasksCompleted: 0,
  habitsCompleted: 0,
  dailiesCompleted: 0,
  monstersDefeated: 0,
  bossesDefeated: 0,
  totalGoldEarned: 0,
  totalDeaths: 0,
  itemsBought: 0,
  history: [],
  currentStreak: 0,
  maxStreak: 0,
  perfectDays: 0,
  waterDrank: 0,
  exerciseDays: 0,
  cardioSessions: 0,
  healthyMeals: 0,
  stepsMax: 0,
  exerciseHours: 0,
  pagesRead: 0,
  languagePractice: 0,
  meditationHours: 0,
  deepWorkSessions: 0,
  journalEntries: 0,
  noSnoozeDays: 0,
  cosmeticsBought: 0,
  petsOwned: 0,
  realLifeRewardsBought: 0,
  lowHpHeals: 0,
  friendsInvited: 0,
};