// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qccmmpfzksscogkmrcag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjY21tcGZ6a3NzY29na21yY2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUzMjY2ODQsImV4cCI6MjA5MDkwMjY4NH0.vyaC4WLPXeRpyvJmXhV_xFiS2aYABG2AlBDR6L9g5Nw";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);